language: java
jdk: openjdk6

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y make cmake 

install:
  - ant -f java/build.xml jar
  - ant -f java/replication/build.xml jar
  - ./contrib/travis/make_cpp_tests.sh

script:
  - source contrib/travis/run_tests.sh

